name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: echo repo
        env:
          REPO: ${{github.repository}}
        run: echo "$REPO"
      - name: echo sha
        env:
          SHA: ${{github.sha}}
        run: echo "$SHA"
      - name: echo actor
        env:
          ACTOR: ${{github.actor}}
        run: echo "$ACTOR"
